### ISSUE TITLE
Testing Program for screenpipe Releases

### ISSUE THREAD

**Issue by louis030195** [mediar-ai/screenpipe#1602]
# Testing Program for Screenpipe Releases

## Overview

We're starting a community testing program for Screenpipe releases to ensure quality across platforms. This proposal outlines how community members can participate and earn rewards for testing.

## Proposal

We'll create a system where:

1. Testers register by adding their GitHub handles to a `TESTERS.md` file
2. New builds needing testing (marked with `release-app-need-test` in commit) automatically notify testers
3. Testers who provide quality feedback with recordings/logs receive $10 compensation

## Implementation Details

1. **Tester Registration**:
   - Create `TESTERS.md` in project root listing GitHub handles of testers
   - Testers join by submitting a PR to add their handle

2. **Workflow Integration**:
   - Modify `.github/workflows/release-app.yml` to detect `release-app-need-test` in commit messages
   - Add post-publish job that creates a testing issue and pings registered testers

3. **Testing Process**:
   - Testers download the new release
   - Test core functionality and report issues
   - Submit feedback including screen recordings and logs
   - Receive $10 compensation per quality testing session

4. **Technical Implementation**:
   - Parse `TESTERS.md` to extract GitHub handles
   - Use GitHub API to create issues and notify testers
   - Track participation and feedback quality

## Draft Workflow Changes

```yml:release-app.yml
# Add to check_commit job outputs
should_test: ${{ steps.check.outputs.should_test }}

# Add to check_commit job steps
- id: check
  run: |
    # Existing checks...
    if echo "$COMMIT_MSG" | grep -q "release-app-need-test"; then
      echo "should_test=true" >> $GITHUB_OUTPUT
    else
      echo "should_test=false" >> $GITHUB_OUTPUT
    fi

# Add new job after publish-release
create-test-issue:
  needs: [check_commit, publish-release]
  if: needs.check_commit.outputs.should_test == 'true'
  runs-on: ubuntu-latest
  permissions:
    issues: write
  steps:
    - uses: actions/checkout@v4
    
    - name: Read TESTERS.md
      id: testers
      run: |
        TESTERS=$(grep -E '^- @[a-zA-Z0-9-]+$' TESTERS.md | tr '\n' ' ')
        echo "tester_list=$TESTERS" >> $GITHUB_OUTPUT
    
    - name: Get version
      run: |
        VERSION=$(grep '^version = ' screenpipe-app-tauri/src-tauri/Cargo.toml | sed 's/version = "\(.*\)"/\1/')
        echo "VERSION=$VERSION" >> $GITHUB_ENV
    
    - name: Create testing issue
      uses: peter-evans/create-issue-from-file@v4
      with:
        title: "Testing needed: Screenpipe v${{ env.VERSION }}"
        content-filepath: .github/ISSUE_TEMPLATE/testing-request.md
        labels: testing
        assignees: ${{ steps.testers.outputs.tester_list }}
```

## Questions to Resolve

1. Where should testers submit their feedback? (Issues, specific form, etc.)
2. How will we track and process the $10 payments?
3. What specific tests should be prioritized?
4. Should we have platform-specific tester groups?

## Next Steps

1. Create `TESTERS.md` file structure
2. Create issue template for testing requests
3. Implement workflow changes
4. Document testing guidelines

Let me know your thoughts on this proposal!

cc @m13v
