### ISSUE TITLE
linux app build is broken

### ISSUE THREAD

**Issue by louis030195** [mediar-ai/screenpipe#324]
https://github.com/mediar-ai/screenpipe/actions/runs/10856633033/job/30131659292

**Comment by jandremarais** [comment]
Hi
I wanted to get over this issue too. It looks like some conflict between the v8 and ort bindings. I don't know what the best solution is but I found that adding this to `.cargo/config.toml` results in a successful build:

```toml
...
[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "link-arg=--allow-multiple-definition"]
```
