### ISSUE TITLE
[bounty] switch pipes engine from deno to bun

### ISSUE THREAD

**Issue by louis030195** [mediar-ai/screenpipe#582]
definition of done:
- all pipes works with new engine (updated if necessary), including the screenpipe-js sdk
- pipes works on all OS - (you tested it, i can test on macos, i cannot test for windows/linux)
- meaning you need to update how we package deno to bun on different OS

why? nextjs does not work well in deno, too many issues, not many upsides (for example https://github.com/vercel/ai-chatbot was crashing in deno when asking AI questions, e.g. SSE not supported or something)

/bounty 100

**Comment by Abiji-2020** [comment]
https://github.com/mediar-ai/screenpipe/blob/main/screenpipe-core/src/pipes.rs

In this we have to implement the bun right from deno

**Comment by kumarvivek1752** [comment]
@louis030195 I added configuration for Bun, and I'm testing the plugin with Bun.

demo bunfig.toml:

```toml
[dependencies]
screenpipe = { url = "https://raw.githubusercontent.com/mediar-ai/screenpipe/main/screenpipe-js/main.ts" }

[imports]
fs = "node:fs"
screenpipe = "https://raw.githubusercontent.com/mediar-ai/screenpipe/main/screenpipe-js/main.ts"
```

`pipe.ts:`

```js
import {
  queryScreenpipe,
  loadPipeConfig,
  ContentItem,
  extractJsonFromLlmResponse,
} from "screenpipe";

console.log("Loading pipe config:", loadPipeConfig());
console.log("Plugin is running");

```

when I try to use `screenpipe package`
```
➜ screenpipe git:(main) bun run --allow-read --allow-write --allow-env --allow-net --allow-run --allow-sys .\examples\typescript\pipe-meeting-summary-by-email\pipe.ts
error: Cannot find package "screenpipe" from "C:\Users\kumar\devlopment\screenpipe\examples\typescript\pipe-meeting-summary-by-email\pipe.ts"

Bun v1.1.29 (Windows x64)
➜ screenpipe git:(main) ✗
```

am I missing something?
